# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Movie.create(title: "Wonder Woman 1984", overview: "Wonder Woman comes into conflict with the Soviet Union during the Cold War in the 1980s", poster_url: "https://image.tmdb.org/t/p/original/8UlWHLMpgZm9bx6QYh0NFoq67TZ.jpg", rating: 6.9)
Movie.create(title: "The Shawshank Redemption", overview: "Framed in the 1940s for double murder, upstanding banker Andy Dufresne begins a new life at the Shawshank prison", poster_url: "https://image.tmdb.org/t/p/original/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg", rating: 8.7)
Movie.create(title: "Titanic", overview: "101-year-old Rose DeWitt Bukater tells the story of her life aboard the Titanic.", poster_url: "https://image.tmdb.org/t/p/original/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg", rating: 7.9)
Movie.create(title: "Ocean's Eight", overview: "Debbie Ocean, a criminal mastermind, gathers a crew of female thieves to pull off the heist of the century.", poster_url: "https://image.tmdb.org/t/p/original/MvYpKlpFukTivnlBhizGbkAe3v.jpg", rating: 7.0)
Movie.create(title: "Aguirre, der Zorn Gottes", overview: "A few decades after the destruction of the Inca Empire, a Spanish expedition led by the infamous Aguirre leaves the mountains of Peru and goes down the Amazon River in search of the lost city of El Dorado. When great difficulties arise, Aguirre’s men start to wonder whether their quest will lead them to prosperity or certain death.", poster_url: "https://image.tmdb.org/t/p/original/6MNqmGe0JjEuGX1PMjRBAEI6aXg.jpg", rating: 7.6)
Movie.create(title: "Rosemary's Baby", overview: "A young couple, Rosemary and Guy, moves into an infamous New York apartment building, known by frightening legends and mysterious events, with the purpose of starting a family.", poster_url: "https://image.tmdb.org/t/p/original/s8pdaHjxNPLXIA1WjSTWm00RJTz.jpg", rating: 7.8)
Movie.create(title: "Blade Runner", overview: "In the smog-choked dystopian Los Angeles of 2019, blade runner Rick Deckard is called out of retirement to terminate a quartet of replicants who have escaped to Earth seeking their creator for a way to extend their short life spans.", poster_url: "https://image.tmdb.org/t/p/original/63N9uy8nd9j7Eog2axPQ8lbr3Wj.jpg", rating: 7.9)
Movie.create(title: "Annihilation", overview: "A biologist signs up for a dangerous, secret expedition into a mysterious zone where the laws of nature don't apply.", poster_url: "https://image.tmdb.org/t/p/original/4YRplSk6BhH6PRuE9gfyw9byUJ6.jpg", rating: 6.4)
Movie.create(title: "They Live", overview: "Nada, a wanderer without meaning in his life, discovers a pair of sunglasses capable of showing the world the way it truly is. As he walks the streets of Los Angeles, Nada notices that both the media and the government are comprised of subliminal messages meant to keep the population subdued, and that most of the social elite are skull-faced aliens bent on world domination. With this shocking discovery, Nada fights to free humanity from the mind-controlling aliens.", poster_url: "https://image.tmdb.org/t/p/original//eIEmSJRKe8Vn9iWcFypvbeyQaZZ.jpg", rating: 7.3)
Movie.create(title: "Der Himmel über Berlin", overview: "Two angels, Damiel and Cassiel, glide through the streets of Berlin, observing the bustling population, providing invisible rays of hope to the distressed but never interacting with them. When Damiel falls in love with lonely trapeze artist Marion, the angel longs to experience life in the physical world, and finds -- with some words of wisdom from actor Peter Falk -- that it might be possible for him to take human form.", poster_url: "https://image.tmdb.org/t/p/original/iZQs2vUeCzvS1KfZJ6uYNCGJBBV.jpg", rating: 7.8)
Movie.create(title: "Die Ehe der Maria Braun", overview: "Maria marries a young soldier in the last days of World War II, only for him to go missing in the war. She must rely on her beauty and ambition to navigate the difficult post-war years alone.", poster_url: "https://image.tmdb.org/t/p/original/tXjZEzlf4WQwZ4Dt53gXeJVuO7p.jpg", rating: 7.5)
Movie.create(title: "Der Baader Meinhof Komplex", overview: "'Der Baader Meinhof Komplex' depicts the political turmoil in the period from 1967 to the bloody 'Deutschen Herbst' in 1977. The movie approaches the events based on Stefan Aust's standard work on the Rote Armee Fraktion (RAF). The story centers on the leadership of the self named anti-fascist resistance to state violence: Andreas Baader, Ulrike Meinhof and Gudrun Ensslin", poster_url: "https://image.tmdb.org/t/p/original/4D1MllpbRMt6DDsSCxQxbl2JYM5.jpg", rating: 7)
Movie.create(title: "The Sword of Doom", overview: "Ryunosuke, a gifted swordsman plying his trade during the turbulent final days of Shogunate rule, has no moral code and kills without remorse. It’s a way of life that leads to madness.", poster_url: "https://image.tmdb.org/t/p/original/uSP0413VhQZFL48NnJ7P8N18shP.jpg", rating: 7.6)
Movie.create(title: "Seven Samurai", overview: "A samurai answers a village's request for protection after he falls on hard times. The town needs protection from bandits, so the samurai gathers six others to help him teach the people how to defend themselves, and the villagers provide the soldiers with food.", poster_url: "https://image.tmdb.org/t/p/original/tGLc7BE56VkIfDJVRoT9GLMBUr9.jpg", rating: 8.5)
Movie.create(title: "Yojimbo", overview: "A nameless ronin, or samurai with no master, enters a small village in feudal Japan where two rival businessmen are struggling for control of the local gambling trade. Taking the name Sanjuro Kuwabatake, the ronin convinces both silk merchant Tazaemon and sake merchant Tokuemon to hire him as a personal bodyguard, then artfully sets in motion a full-scale gang war between the two ambitious and unscrupulous men.", poster_url: "https://image.tmdb.org/t/p/original/tN7kYPjRhDolpui9sc9Eq9n5b2O.jpg", rating: 8.2)
Movie.create(title: "Barry Lyndon", overview: "An Irish rogue uses his cunning and wit to work his way up the social classes of 18th century England, transforming himself from the humble Redmond Barry into the noble Barry Lyndon.", poster_url: "https://image.tmdb.org/t/p/original/3YJEv83HWWgCKezTiQ9LhdR7cFU.jpg", rating: 8)
Movie.create(title: "Mulholland Drive", overview: "Blonde Betty Elms has only just arrived in Hollywood to become a movie star when she meets an enigmatic brunette with amnesia. Meanwhile, as the two set off to solve the second woman's identity, filmmaker Adam Kesher runs into ominous trouble while casting his latest project.", poster_url: "https://image.tmdb.org/t/p/original/tVxGt7uffLVhIIcwuldXOMpFBPX.jpg", rating: 7.8)

# Movie.create(title: "", overview: "", poster_url: "https://image.tmdb.org/t/p/original/", rating: )
# Movie.create(title: "", overview: "", poster_url: "https://image.tmdb.org/t/p/original/", rating: )
# Movie.create(title: "", overview: "", poster_url: "https://image.tmdb.org/t/p/original/", rating: )
# Movie.create(title: "", overview: "", poster_url: "https://image.tmdb.org/t/p/original/", rating: )
# 大菩薩峠
# 七人の侍
# 用心棒
